### ISSUE TITLE
Helmet Middleware Blocks Dev Server Hot Refresh

### ISSUE THREAD

**Issue by joelhickok** [skyf0l/sveltekit-helmet#33]
Thanks for the work on this.  It will be useful!

This middleware breaks "hot refresh" in the browser window when used either as a single hook, or in sequence.

I think that the handler may not be resolving correctly.  Not sure.  As soon as I remove the svelte-helmet middleware and restart my dev server, hot refresh starts working again.

Using:
svelte 5.1.7
@sveltejs/kit 2.7.3
sveltekit-helmet 2.0.0
vite 5.4.10

**Comment by skyf0l** [comment]
Hello, I never noticed this before because on my project that uses it, the hot refresh works fine, but when trying with a minimal sveltekit template, the hot reload no longer works. I'll dig into this problem.

**Comment by skyf0l** [comment]
hello @joelhickok, I'm back with a solution :tada: 

It seems that the default CSP configuration of helmet is blocking the hot refresh script, you can see that in the console:
![image](https://github.com/user-attachments/assets/03f0ccd8-6128-4ce5-9a31-4f48ab1939fc)

So you must allow it using:
```ts
// src/hooks.server.ts

export const handle = helmet({
  contentSecurityPolicy: {
    directives: {
      scriptSrc: [
        "'self'",
        "'unsafe-inline'", // Allow SvelteKit hot reload
      ],
    },
  },
});
```

I'll add a warning if not set in dev mode

**Comment by joelhickok** [comment]
Great @skyf0l !  This works fine.  Thank you for the fix.
